{% set name = "fastai" %}
{% set version = "2.7.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastai-{{ version }}.tar.gz
  sha256: b20593dbcae7522f1d77a8f5163d1fd60314f292640496804dc356e41cb36454

build:
  entry_points:
    - configure_accelerate=fastai.distributed:configure_accelerate
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - packaging
    - fastdownload >=0.0.5,<2
    - fastcore >=1.5.29,<1.8
    - torchvision >=0.11
    - matplotlib-base
    - pandas
    - requests
    - pyyaml
    - fastprogress >=0.2.4
    - pillow >=9.0.0
    - scikit-learn
    - scipy
    - spacy <4
    - pytorch >=1.10,<2.6

test:
  imports:
    - fastai
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fastai/fastai
  summary: fastai simplifies training fast and accurate neural nets using modern best practices
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
