{% set name = "fastai" %}
{% set version = "2.7.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastai-{{ version }}.tar.gz
  sha256: 317358bf8e0f6147d81be255dfa918d3340ee0b98796e9fae8f8a5d266234b98

build:
  entry_points:
    - configure_accelerate=fastai.distributed:configure_accelerate
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - packaging
    - fastdownload >=0.0.5,<2
    - fastcore >=1.5.29,<1.6
    - torchvision >=0.11
    - matplotlib-base
    - pandas
    - requests
    - pyyaml
    - fastprogress >=0.2.4
    - pillow >=9.0.0
    - scikit-learn
    - scipy
    - spacy <4
    - pytorch >=1.10,<2.5

test:
  imports:
    - fastai
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastai
  summary: fastai simplifies training fast and accurate neural nets using modern best practices
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
