{% set name = "fastai" %}
{% set version = "2.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastai-{{ version }}.tar.gz
  sha256: e5ac80ff46dd8070c670a348f31a64c85ea1a91dc320c2106488f34333282916

build:
  entry_points:
    - configure_accelerate=fastai.distributed:configure_accelerate
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pip
    - packaging
    - fastdownload >=0.0.5,<2
    - fastcore >=1.3.8
    - torchvision >=0.8.0
    - matplotlib-base
    - pandas
    - requests
    - pyyaml
    - fastprogress >=0.2.4
    - pillow >6.0.0
    - scikit-learn
    - scipy
    - spacy <4
    - pytorch >=1.7.0

test:
  imports:
    - fastai
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/fastai/fastai
  summary: fastai simplifies training fast and accurate neural nets using modern best practices
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
